name: Update Profile
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Update recent activity
        uses: jamesgeorge007/github-activity-readme@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: ${{ github.repository_owner }}
          COMMIT_COUNT: 10
          MAX_LINES: 15
          
      - name: Update recent repositories
        uses: varunsridharan/action-repos-to-readme@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_REPOS: 6
          EXCLUDE_REPOS: "SIDNEY081"
          HEADER: "### 🚀 Recent Projects\n"
          STYLE: "vertical"
          FIELDS: "name,description,updated,url"
