name: Update Profile
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Debug - List files
        run: ls -la
          
      - name: Update README
        run: |
          echo "### ⚡ Recent Activity" > test_section.md
          echo "" >> test_section.md
          echo "<!--START_SECTION:activity-->" >> test_section.md
          echo "✅ **Sidney081 - Dynamic Update**" >> test_section.md
          echo "🕒 Updated: $(date)" >> test_section.md
          echo "1. 🔨 SafeShell Android app" >> test_section.md
          echo "2. 🧠 AI-Stroke-Shield project" >> test_section.md
          echo "<!--END_SECTION:activity-->" >> test_section.md
          
          # Replace the section in README
          python3 << 'EOF'
import re
with open('README.md', 'r') as f:
    content = f.read()
    
with open('test_section.md', 'r') as f:
    new_section = f.read()
    
# Replace the entire activity section
pattern = r'### ⚡ Recent Activity\s*<!--START_SECTION:activity-->.*?<!--END_SECTION:activity-->'
new_content = re.sub(pattern, new_section, content, flags=re.DOTALL)

with open('README.md', 'w') as f:
    f.write(new_content)
    
print("✅ README updated successfully!")
EOF
          
      - name: Show changes
        run: git diff
          
      - name: Commit and push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add README.md
          git commit -m "✅ Update Sidney081 profile - $(date)" || echo "No changes to commit"
          git push
