name: Update Profile
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'  # Daily at 9 AM

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update activity with Python script
        run: python .github/scripts/update_activity.py
          
      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add README.md
          git diff --staged --quiet || git commit -m "🔄 Update Sidney081 activity - $(date)"
          git push
